[project]
name = "pdf-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "pymupdf>=1.26.6",
    "reportlab>=4.4.5",
    "tqdm>=4.67.1",
]
